export type stringToStringListDict = {
    [key: string]: string[]
}

export type stringToIntDict = {
    [key: string]: number
}

export let sectionToBookDict: stringToStringListDict = {
    "pentateuch": ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"],
    "history": ["Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther"],
    "wisdom": ["Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Songs"],
    "major_ prophets": ["Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel"],
    "minor_prophets": ["Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi"],
    "gospels_acts": ["Matthew", "Mark", "Luke", "John", "Acts"],
    "other_nt": ["Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians", "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation"]
}

export let bookToChapterDict: stringToIntDict = {
    "Genesis": 50,
    "Exodus": 40,
    "Leviticus": 27,
    "Numbers": 36,
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1 Samuel": 31,
    "2 Samuel": 24,
    "1 Kings": 22,
    "2 Kings": 25,
    "1 Chronicles": 29,
    "2 Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Esther": 10,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song of Songs": 8,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Ezekiel": 48,
    "Daniel": 12,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1 Corinthians": 16,
    "2 Corinthians": 13,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1 Thessalonians": 5,
    "2 Thessalonians": 3,
    "1 Timothy": 6,
    "2 Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1 Peter": 5,
    "2 Peter": 3,
    "1 John": 5,
    "2 John": 1,
    "3 John": 1,
    "Jude": 1,
    "Revelation": 22
}


export let bookToIDDict = {
    "Genesis": "001",
    "Exodus": "002",
    "Leviticus": "003",
    "Numbers": "004",
    "Deuteronomy": "005",
    "Joshua": "006",
    "Judges": "007",
    "Ruth": "008",
    "1 Samuel": "009",
    "2 Samuel": "010",
    "1 Kings": "011",
    "2 Kings": "012",
    "1 Chronicles": "013",
    "2 Chronicles": "014",
    "Ezra": "015",
    "Nehemiah": "016",
    "Esther": "017",
    "Job": "018",
    "Psalms": "019",
    "Proverbs": "020",
    "Ecclesiastes": "021",
    "Song of Songs": "022",
    "Isaiah": "023",
    "Jeremiah": "024",
    "Lamentations": "025",
    "Ezekiel": "026",
    "Daniel": "027",
    "Hosea": "028",
    "Joel": "029",
    "Amos": "030",
    "Obadiah": "031",
    "Jonah": "032",
    "Micah": "033",
    "Nahum": "034",
    "Habakkuk": "035",
    "Zephaniah": "036",
    "Haggai": "037",
    "Zechariah": "038",
    "Malachi": "039",
    "Matthew": "040",
    "Mark": "041",
    "Luke": "042",
    "John": "043",
    "Acts": "044",
    "Romans": "045",
    "1 Corinthians": "046",
    "2 Corinthians": "047",
    "Galatians": "048",
    "Ephesians": "049",
    "Philippians": "050",
    "Colossians": "051",
    "1 Thessalonians": "052",
    "2 Thessalonians": "053",
    "1 Timothy": "054",
    "2 Timothy": "055",
    "Titus": "056",
    "Philemon": "057",
    "Hebrews": "058",
    "James": "059",
    "1 Peter": "060",
    "2 Peter": "061",
    "1 John": "062",
    "2 John": "063",
    "3 John": "064",
    "Jude": "065",
    "Revelation": "066"
}